[build]
  command = "yarn download-s3 && yarn build"
  publish = ".next"

[context.production]
  environment = { NODE_VERSION = "16.14.2" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.14.2" }

[context.branch-deploy]
  environment = { NODE_VERSION = "16.14.2" }
