[build]
  command = "npm run download-s3 && npm run build"
  publish = "_site"

[context.production]
  environment = { NODE_VERSION = "20.18.0" }

[context.deploy-preview]
  environment = { NODE_VERSION = "20.18.0" }

[context.branch-deploy]
  environment = { NODE_VERSION = "20.18.0" }
