version: 2.1

orbs:
    aws-cli: circleci/aws-cli@2.0.2

jobs:
    build:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - checkout
            - restore_cache:
                name: Restore Yarn Package Cache
                keys:
                    - yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                name: Install Dependencies
                command: yarn install --immutable
            - run:
                name: Sync Down S3 Objects
                command: yarn download-s3
            - run:
                name: Build Static Site
                command: |
                  yarn build
                  yarn export
            - save_cache:
                name: Save Yarn Package Cache
                key: yarn-packages-{{ checksum "yarn.lock" }}
                paths:
                    - ~/.cache/yarn
            - persist_to_workspace:
                root: .
                paths:
                    - out
    deploy:
        machine:
            image: ubuntu-2004:202010-01
        steps:
            - attach_workspace:
                at: .
            - aws-cli/setup
            - run: |
                aws s3 ls
                ls -laR out

workflows:
    version: 2
    build-deploy:
        jobs:
            - build
            - deploy:
                context: aws
                requires:
                    - build
                filters:
                    branches:
                        only: main
