name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    environment: Production
    # Available tools on this machine:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Export ENV Vars for Node
        run: |
          export KITA_AWS_REGION=${{ env.KITA_AWS_REGION }}
          export KITA_S3_REPOSITORY=${{ env.KITA_S3_REPOSITORY }}
          export KITA_AWS_ACCESS_KEY_ID=${{ env.KITA_AWS_ACCESS_KEY_ID }}
          export KITA_AWS_SECRET_ACCESS_KEY=${{ env.KITA_AWS_SECRET_ACCESS_KEY }}
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Sync Down S3 Objects
        run: yarn download-s3
      - name: Build Static Site
        run: |
          yarn build
          yarn export
      # https://github.com/actions/upload-artifact
      - name: Upload Dist Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: out
  deploy:
    # Loosely speaking, this is a "Production" check for this runner
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: Production
    name: Deploy Steps
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Export ENV Vars for Node
        run: |
          export KITA_AWS_REGION=${{ env.KITA_AWS_REGION }}
          export KITA_S3_REPOSITORY=${{ env.KITA_S3_REPOSITORY }}
          export KITA_AWS_ACCESS_KEY_ID=${{ env.KITA_AWS_ACCESS_KEY_ID }}
          export KITA_AWS_SECRET_ACCESS_KEY=${{ env.KITA_AWS_SECRET_ACCESS_KEY }}
      # https://github.com/actions/download-artifact
      - name: Download Dist Artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
      - name: List Dist
        run: ls -laR out
      - name: AWS S3 Object List
        run: aws s3 ls
