name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    environment: Production
    # Available tools on this machine:
    # https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install, test and build dist
        run: |
          echo KITA_AWS_REGION="${{ secrets.KITA_AWS_REGION }}" >> .env.production.local
          echo KITA_S3_REPOSITORY="${{ secrets.KITA_S3_REPOSITORY }}">> .env.production.local
          echo KITA_AWS_ACCESS_KEY_ID="${{ secrets.KITA_AWS_ACCESS_KEY_ID }}">> .env.production.local
          echo KITA_AWS_SECRET_ACCESS_KEY="${{ secrets.KITA_AWS_SECRET_ACCESS_KEY }}">> .env.production.local
          yarn install --immutable
          yarn download
          yarn build
          yarn export
      # https://github.com/actions/upload-artifact
      - name: Upload job artifact
        uses: actions/upload-artifact@v2
        with:
          name: job-artifact
          path: |
            ${{ github.workspace }}/out/
  deploy:
    # Loosely speaking, this is a "Production" check for this runner
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      # https://github.com/actions/download-artifact
      - name: Download job artifact
        uses: actions/download-artifact@v2
        with:
          name: job-artifact
      - name: Deploy dist
        run: |
          ls -laR out
